version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  build-deploy:
    jobs:
  deploy-staging:
    - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  deploy-prod:
    - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY2@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-staging:
          requires:
            - build
            - test
          filters:
            branches:
              only: staging
          context: staging

      - deploy-prod:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
          context: prodution
