version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13.0

    steps:
      - checkout
      - run: npm install
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME2.git master

  deploy-stage:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME1.git sample:master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: sample
